kalibr-tools-melodic:
	@docker build -f ./Dockerfile.melodic -t quadcam-calib:melodic .

kalibr-tools-noetic:
	@docker build -f ./Dockerfile.noetic -t quadcam-calib:noetic .

all: kalibr-tools-melodic
